// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

class Assets {
  const Assets._();
  static const String assets_fair_lib_src_page_list_builder_fair_bin =
      'assets/fair/lib_src_page_list_builder.fair.bin';

  static const String assets_fair_lib_src_page_list_builder_fair_js =
      'assets/fair/lib_src_page_list_builder.fair.js';

  static const String assets_fair_lib_src_page_photo_gallery_fair_bin =
      'assets/fair/lib_src_page_photo_gallery.fair.bin';

  static const String assets_fair_lib_src_page_photo_gallery_fair_js =
      'assets/fair/lib_src_page_photo_gallery.fair.js';

  static const String assets_fair_lib_src_page_photo_gallery1_fair_bin =
      'assets/fair/lib_src_page_photo_gallery1.fair.bin';

  static const String assets_fair_lib_src_page_photo_gallery1_fair_js =
      'assets/fair/lib_src_page_photo_gallery1.fair.js';

  static const String assets_fair_lib_src_page_photo_gallery_item_fair_bin =
      'assets/fair/lib_src_page_photo_gallery_item.fair.bin';

  static const String assets_fair_lib_src_page_photo_gallery_item_fair_js =
      'assets/fair/lib_src_page_photo_gallery_item.fair.js';

  static const String assets_fair_lib_src_page_photo_swiper_fair_bin =
      'assets/fair/lib_src_page_photo_swiper.fair.bin';

  static const String assets_fair_lib_src_page_photo_swiper_fair_js =
      'assets/fair/lib_src_page_photo_swiper.fair.js';

  /// {@macro assets_generator.assets_image_40_png.preview}
  static const String assets_image_40_png = 'assets/image/40.png';

  /// {@macro assets_generator.assets_image_avatar_jpg.preview}
  static const String assets_image_avatar_jpg = 'assets/image/avatar.jpg';

  /// {@macro assets_generator.assets_image_fluttercandies_grey_png.preview}
  static const String assets_image_fluttercandies_grey_png =
      'assets/image/flutterCandies_grey.png';

  /// {@macro assets_generator.assets_image_loading_gif.preview}
  static const String assets_image_loading_gif = 'assets/image/loading.gif';

  /// {@macro assets_generator.assets_image_love_png.preview}
  static const String assets_image_love_png = 'assets/image/love.png';

  /// {@macro assets_generator.assets_image_sun_glasses_png.preview}
  static const String assets_image_sun_glasses_png =
      'assets/image/sun_glasses.png';

  static const String assets_plugin_fair_common_plugin_js =
      'assets/plugin/fair_common_plugin.js';
}
