// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// version: 10.0.8
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import,unnecessary_import,unused_shown_name,implementation_imports,duplicate_import
import 'package:fair_gallery/src/widget/extended_fair_widget.dart';
import 'package:flutter/foundation.dart';

/// The routeNames auto generated by https://github.com/fluttercandies/ff_annotation_route
const List<String> routeNames = <String>[
  'MainPage',
  'PhotoGalleryItem',
  'PhotoGalleryPage',
  'PhotoGalleryPage1',
  'PhotoSwiper',
];

/// The routes auto generated by https://github.com/fluttercandies/ff_annotation_route
class Routes {
  const Routes._();

  /// 'MainPage'
  ///
  /// [name] : 'MainPage'
  ///
  /// [routeName] : 'MainPage'
  ///
  /// [exts] : {'ffRouteFileImport': 'package:fair_gallery/src/main_page.dart'}
  static const _MainPage mainPage = _MainPage();

  /// 'PhotoGalleryItem'
  ///
  /// [name] : 'PhotoGalleryItem'
  ///
  /// [routeName] : '图片列表单个元素'
  ///
  /// [description] : 'PhotoGalleryItem'
  ///
  /// [constructors] :
  ///
  /// PhotoGalleryItem : [Map<String, dynamic>(required) fairProps]
  ///
  /// [exts] : {ExtendedFairWidget.tag: true, 'ffRouteFileImport': 'package:fair_gallery/src/page/photo_gallery_item.dart'}
  static const _PhotoGalleryItem photoGalleryItem = _PhotoGalleryItem();

  /// '展示如何使用Fair创建一个列表'
  ///
  /// [name] : 'PhotoGalleryPage'
  ///
  /// [routeName] : '照片库列表'
  ///
  /// [description] : '展示如何使用Fair创建一个列表'
  ///
  /// [exts] : {ExtendedFairWidget.tag: true, 'ffRouteFileImport': 'package:fair_gallery/src/page/photo_gallery.dart'}
  static const _PhotoGalleryPage photoGalleryPage = _PhotoGalleryPage();

  /// '展示如何使用Fair创建一个列表1'
  ///
  /// [name] : 'PhotoGalleryPage1'
  ///
  /// [routeName] : '照片库列表1'
  ///
  /// [description] : '展示如何使用Fair创建一个列表1'
  ///
  /// [exts] : {ExtendedFairWidget.tag: true, 'ffRouteFileImport': 'package:fair_gallery/src/page/photo_gallery1.dart'}
  static const _PhotoGalleryPage1 photoGalleryPage1 = _PhotoGalleryPage1();

  /// '图片预览页面'
  ///
  /// [name] : 'PhotoSwiper'
  ///
  /// [routeName] : 'PhotoSwiper'
  ///
  /// [description] : '图片预览页面'
  ///
  /// [constructors] :
  ///
  /// PhotoSwiper : [Map<String, dynamic>(required) fairProps]
  ///
  /// [pageRouteType] : PageRouteType.transparent
  ///
  /// [exts] : {ExtendedFairWidget.tag: true, 'ffRouteFileImport': 'package:fair_gallery/src/page/photo_swiper.dart'}
  static const _PhotoSwiper photoSwiper = _PhotoSwiper();
}

class _MainPage {
  const _MainPage();

  String get name => 'MainPage';

  Map<String, dynamic> d({
    Key? key,
  }) =>
      <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _PhotoGalleryItem {
  const _PhotoGalleryItem();

  String get name => 'PhotoGalleryItem';

  Map<String, dynamic> d({
    Key? key,
    required Map<String, dynamic> fairProps,
  }) =>
      <String, dynamic>{
        'key': key,
        'fairProps': fairProps,
      };

  @override
  String toString() => name;
}

class _PhotoGalleryPage {
  const _PhotoGalleryPage();

  String get name => 'PhotoGalleryPage';

  Map<String, dynamic> d({
    Key? key,
  }) =>
      <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _PhotoGalleryPage1 {
  const _PhotoGalleryPage1();

  String get name => 'PhotoGalleryPage1';

  Map<String, dynamic> d({
    Key? key,
  }) =>
      <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _PhotoSwiper {
  const _PhotoSwiper();

  String get name => 'PhotoSwiper';

  Map<String, dynamic> d({
    Key? key,
    required Map<String, dynamic> fairProps,
  }) =>
      <String, dynamic>{
        'key': key,
        'fairProps': fairProps,
      };

  @override
  String toString() => name;
}
